;; 0002 Even Fibonacci numbers

;; http://projecteuler.net/index.php?section=problems&id=2
;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; Find the sum of all the even-valued terms in the sequence which do not exceed four million.

;; http://odz.sakura.ne.jp/projecteuler/index.php?Problem%202
;; フィボナッチ数列の項は前の2つの項の和である. 最初の2項を 1, 2 とすれば, 最初の10項は以下の通りである.

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; 数列の項の値が400万より小さい, 偶数値の項の総和を求めよ.

;; Note:この問題は最近更新されました. お使いのパラメータが正しいかどうか確認してください.


;; from sicp 1.19
(define (fib n)
  (let rec ((a 1)(b 1)(p 0)(q 1)(count n))
    (cond ((= count 0) b)
          ((even? count)
           (rec a
                b
                (+ (* p p) (* q q))
                (+ (* 2 p q) (* q q))
                (/ count 2)))
          (else (rec (+ (* b q) (* a q) (* a p))
                     (+ (* b p) (* a q))
                     p
                     q
                     (- count 1))))))

(print
 (apply + (filter-map
           (^x (and-let* ((n (fib x))
                          ((<= n (* 4 (expt 10 6))))
                          ((even? n)))
                 n))
           (iota 33 1))))
